# Site settings
title: Francesco Paolo Severino
author:
  name: Francesco Paolo Severino
description: Computer Engineering student
baseurl: ""
url: "https://fpseverino.com"
twitter_username: fp_severino
github_username: fpseverino

# Build settings
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Theme-specific settings

minima:
  skin: dark
  social_links:
    - title: Francesco Paolo Severino at GitHub
      icon: github
      url: "https://github.com/fpseverino"
    - title: Francesco Paolo Severino at Linkedin
      icon: linkedin
      url: "https://www.linkedin.com/in/fpseverino"
    - title: Francesco Paolo Severino at Mastodon
      icon: mastodon
      url: "https://mastodon.social/@fpseverino"
    - title: Francesco Paolo Severino at Instagram
      icon: instagram
      url: "https://www.instagram.com/fp.severino"
    - title: Francesco Paolo Severino at Facebook
      icon: facebook
      url: "https://www.facebook.com/fpseverino.it/"
    - title: Francesco Paolo Severino at X (formerly Twitter)
      icon: x-twitter
      url: "https://twitter.com/fp_severino"
    - title: Francesco Paolo Severino at Stack Overflow
      icon: stack-overflow
      url: "https://stackoverflow.com/users/10176094/francesco-paolo-severino"

header_pages:
  - PRIVACY-POLICY.md
